---

- name: Configure hosts & deploy application # <-- Словесное описание сценария (name)
  hosts: all # <-- Для каких хостов будут выполняться описанные ниже таски (hosts)
  vars:
    mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
    db_host: 192.168.10.20 # <-- подставьте сюда ваш IP
  tasks: # <-- Блок тасков (заданий), которые будут выполняться для данных хостов

    - name: Change mongo config file
      become: true # <-- Выполнить задание от root
      template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongod.conf # <-- Путь на удаленном хосте
        mode: "0644" # <-- Права на файл, которые нужно установить
      tags: db-tag # <-- Список тэгов для задачи
      notify: Restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: "0644"
      tags: app-tag
      notify: Reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        mode: "0664"
      tags: app-tag

    - name: Enable puma
      become: true
      systemd:
        name: puma
        enabled: true
      tags: app-tag

    - name: Install git
      become: true
      apt:
        name: git
        state: present
      tags: deploy-tag

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: Reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle
      tags: deploy-tag

  handlers:
    - name: Restart mongod
      become: true
      service:
        name: mongod
        state: restarted
    - name: Reload puma
      become: true
      systemd:
        name: puma
        state: restarted
